name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Deploy to Cloudflare
      env:
        CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: |
        npm run deploy 2>&1 | sed -E 's#https://[a-zA-Z0-9.-]+\.workers\.dev#[REDACTED]#g'